#define FPA_MESSAGEUI_IDC_SENDBUTTON     33500
#define FPA_MESSAGEUI_IDC_CUSTOMCHATTEXT 33601

#define FPA_MESSAGEUI_UISIZESMALL        0.55
#define FPA_MESSAGEUI_UISCALE            ((getResolution select 5)/FPA_MESSAGEUI_UISIZESMALL)

#define FPA_MESSAGEUI_SCALEFACTOR_Y      ((((safezoneW / safezoneH) min 1.2) / 1.2) / 25)
#define FPA_MESSAGEUI_SCALESUMMAND_Y     (safezoneY)

#define FPA_MESSAGEUI_SCALEFACTOR_X      (((safezoneW / safezoneH) min 1.2) / 40)
#define FPA_MESSAGEUI_SCALESUMMAND_X     (safezoneX)

#define FPA_MESSAGEUI_SPACER_Y           (0.1 * FPA_MESSAGEUI_SCALEFACTOR_Y)

#define FPA_MESSAGEUI_TITLE_Y            (1 * FPA_MESSAGEUI_SCALEFACTOR_Y + FPA_MESSAGEUI_SCALESUMMAND_Y)
#define FPA_MESSAGEUI_TITLE_X            (1 *  FPA_MESSAGEUI_SCALEFACTOR_X + FPA_MESSAGEUI_SCALESUMMAND_X)

#define FPA_MESSAGEUI_ELEMENT_H          (1 * FPA_MESSAGEUI_SCALEFACTOR_Y)
#define FPA_MESSAGEUI_TOTAL_W            (15 * FPA_MESSAGEUI_SCALEFACTOR_X)

#define FPA_MESSAGEUI_EDITBOX_BG_Y       (FPA_MESSAGEUI_TITLE_Y + FPA_MESSAGEUI_ELEMENT_H + FPA_MESSAGEUI_SPACER_Y)
#define FPA_MESSAGEUI_EDITBOX_BG_H       ((8 * FPA_MESSAGEUI_ELEMENT_H) / FPA_MESSAGEUI_UISCALE)

#define FPA_MESSAGEUI_EDITBOX_PADDING_Y  ((0.5 * FPA_MESSAGEUI_ELEMENT_H) / FPA_MESSAGEUI_UISCALE)
#define FPA_MESSAGEUI_EDITBOX_H          (FPA_MESSAGEUI_EDITBOX_BG_H - 2 * FPA_MESSAGEUI_EDITBOX_PADDING_Y)
#define FPA_MESSAGEUI_EDITBOX_Y          (FPA_MESSAGEUI_EDITBOX_BG_Y + FPA_MESSAGEUI_EDITBOX_PADDING_Y)

#define FPA_MESSAGEUI_EDITBOX_PADDING_X  (0.5 * (((safezoneW / safezoneH) min 1.2) / 40))
#define FPA_MESSAGEUI_EDITBOX_X          (FPA_MESSAGEUI_TITLE_X + FPA_MESSAGEUI_EDITBOX_PADDING_X)
#define FPA_MESSAGEUI_EDITBOX_W          (FPA_MESSAGEUI_TOTAL_W - 2 * FPA_MESSAGEUI_EDITBOX_PADDING_X)

#define FPA_MESSAGEUI_SENDBUTTON_Y       (FPA_MESSAGEUI_EDITBOX_BG_Y + FPA_MESSAGEUI_EDITBOX_BG_H + FPA_MESSAGEUI_SPACER_Y)
#define FPA_MESSAGEUI_SENDBUTTON_Y_2     (FPA_MESSAGEUI_EDITBOX_BG_Y + FPA_MESSAGEUI_EDITBOX_BG_H + 2*FPA_MESSAGEUI_SPACER_Y + FPA_MESSAGEUI_ELEMENT_H)
